# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/oidcat/Linux_deployment/WCH/ch347

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/oidcat/Linux_deployment/WCH/ch347

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/oidcat/Linux_deployment/WCH/ch347/CMakeFiles /home/oidcat/Linux_deployment/WCH/ch347/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/oidcat/Linux_deployment/WCH/ch347/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named xvcd_ch347_amd64

# Build rule for target.
xvcd_ch347_amd64: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xvcd_ch347_amd64
.PHONY : xvcd_ch347_amd64

# fast build rule for target.
xvcd_ch347_amd64/fast:
	$(MAKE) -f CMakeFiles/xvcd_ch347_amd64.dir/build.make CMakeFiles/xvcd_ch347_amd64.dir/build
.PHONY : xvcd_ch347_amd64/fast

ch347_xvcd_api.o: ch347_xvcd_api.c.o

.PHONY : ch347_xvcd_api.o

# target to build an object file
ch347_xvcd_api.c.o:
	$(MAKE) -f CMakeFiles/xvcd_ch347_amd64.dir/build.make CMakeFiles/xvcd_ch347_amd64.dir/ch347_xvcd_api.c.o
.PHONY : ch347_xvcd_api.c.o

ch347_xvcd_api.i: ch347_xvcd_api.c.i

.PHONY : ch347_xvcd_api.i

# target to preprocess a source file
ch347_xvcd_api.c.i:
	$(MAKE) -f CMakeFiles/xvcd_ch347_amd64.dir/build.make CMakeFiles/xvcd_ch347_amd64.dir/ch347_xvcd_api.c.i
.PHONY : ch347_xvcd_api.c.i

ch347_xvcd_api.s: ch347_xvcd_api.c.s

.PHONY : ch347_xvcd_api.s

# target to generate assembly for a file
ch347_xvcd_api.c.s:
	$(MAKE) -f CMakeFiles/xvcd_ch347_amd64.dir/build.make CMakeFiles/xvcd_ch347_amd64.dir/ch347_xvcd_api.c.s
.PHONY : ch347_xvcd_api.c.s

io_ch347.o: io_ch347.c.o

.PHONY : io_ch347.o

# target to build an object file
io_ch347.c.o:
	$(MAKE) -f CMakeFiles/xvcd_ch347_amd64.dir/build.make CMakeFiles/xvcd_ch347_amd64.dir/io_ch347.c.o
.PHONY : io_ch347.c.o

io_ch347.i: io_ch347.c.i

.PHONY : io_ch347.i

# target to preprocess a source file
io_ch347.c.i:
	$(MAKE) -f CMakeFiles/xvcd_ch347_amd64.dir/build.make CMakeFiles/xvcd_ch347_amd64.dir/io_ch347.c.i
.PHONY : io_ch347.c.i

io_ch347.s: io_ch347.c.s

.PHONY : io_ch347.s

# target to generate assembly for a file
io_ch347.c.s:
	$(MAKE) -f CMakeFiles/xvcd_ch347_amd64.dir/build.make CMakeFiles/xvcd_ch347_amd64.dir/io_ch347.c.s
.PHONY : io_ch347.c.s

xvcd.o: xvcd.c.o

.PHONY : xvcd.o

# target to build an object file
xvcd.c.o:
	$(MAKE) -f CMakeFiles/xvcd_ch347_amd64.dir/build.make CMakeFiles/xvcd_ch347_amd64.dir/xvcd.c.o
.PHONY : xvcd.c.o

xvcd.i: xvcd.c.i

.PHONY : xvcd.i

# target to preprocess a source file
xvcd.c.i:
	$(MAKE) -f CMakeFiles/xvcd_ch347_amd64.dir/build.make CMakeFiles/xvcd_ch347_amd64.dir/xvcd.c.i
.PHONY : xvcd.c.i

xvcd.s: xvcd.c.s

.PHONY : xvcd.s

# target to generate assembly for a file
xvcd.c.s:
	$(MAKE) -f CMakeFiles/xvcd_ch347_amd64.dir/build.make CMakeFiles/xvcd_ch347_amd64.dir/xvcd.c.s
.PHONY : xvcd.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... xvcd_ch347_amd64"
	@echo "... edit_cache"
	@echo "... ch347_xvcd_api.o"
	@echo "... ch347_xvcd_api.i"
	@echo "... ch347_xvcd_api.s"
	@echo "... io_ch347.o"
	@echo "... io_ch347.i"
	@echo "... io_ch347.s"
	@echo "... xvcd.o"
	@echo "... xvcd.i"
	@echo "... xvcd.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

